### ISSUE TITLE
float16.js: unknown Statement of type "ForOfStatement"

### ISSUE THREAD

**Issue by MtnBiker** [petamoriken/float16#831]
`Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: ~project/node_modules/@petamoriken/float16/browser/float16.js: unknown Statement of type "ForOfStatement"`

Since this hasn't been reported before, I suspect the issue is elsewhere.

@petamoriken/float16 which is a dependency of geotiff which is a dependency of OpenLayers

Complete error from Chrome

olPersonMap.js:487 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /myApp/node_modules/@petamoriken/float16/browser/float16.js: unknown Statement of type "ForOfStatement"
    at Ep.explodeStatement (:3000/myApp/node_modules/regenerator-transform/lib/emit.js:541:13)
    at :3000/myApp/node_modules/regenerator-transform/lib/emit.js:305:12
    at Array.forEach (<anonymous>)
    at Ep.explodeStatement (:3000/myApp/node_modules/regenerator-transform/lib/emit.js:304:22)
    at Ep.explode (:3000/myApp/node_modules/regenerator-transform/lib/emit.js:268:40)
    at PluginPass.<anonymous> (:3000/myApp/node_modules/regenerator-transform/lib/visit.js:98:17)
    at PluginPass.<anonymous> (:3000/myApp/node_modules/regenerator-transform/lib/util.js:25:17)
    at newFn (:3000/myApp/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:92:8)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:3000/myApp/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (:3000/myApp/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:3000/myApp/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (:3000/myApp/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:3000/myApp/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (:3000/myApp/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitSingle (:3000/myApp/node_modules/@babel/traverse/lib/context.js:72:19)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:121:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (:3000/myApp/node_modules/@babel/traverse/lib/path/context.js:90:52)
    at TraversalContext.visitQueue (:3000/myApp/node_modules/@babel/traverse/lib/context.js:96:16)
    at TraversalContext.visitMultiple (:3000/myApp/node_modules/@babel/traverse/lib/context.js:67:17)
    at TraversalContext.visit (:3000/myApp/node_modules/@babel/traverse/lib/context.js:119:19)
    at traverseNode (:3000/myApp/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at ./node_modules/@petamoriken/float16/browser/float16.js (olPersonMap.js:487:1)
    at __webpack_require__ (bootstrap:63:1)
    at ./node_modules/geotiff/dist-module/geotiffimage.js (geotiffimage.js:1:1)
    at __webpack_require__ (bootstrap:63:1)
    at ./node_modules/geotiff/dist-module/geotiff.js (geotiff.js:1:1)
    at __webpack_require__ (bootstrap:63:1)
    at ./node_modules/ol/source/GeoTIFF.js (GeoTIFF.js:1:1)
    at __webpack_require__ (bootstrap:63:1)
    at ./node_modules/ol/source.js (source.js:1:1)
    at __webpack_require__ (bootstrap:63:1)

**Comment by MtnBiker** [comment]
As expected it nothing to do with this. 

Some interaction with having `import OSM from 'ol/source/OSM';` in the main JavaScript and in an imported JavaScript, but wasn't being used in the main Javascript. Took me a couple of hours of trial and error to pin down the problem area..
